### ISSUE TITLE
Style: align verbs in does/doesn't ?

### ISSUE THREAD

**Issue by clausmullie** [publiccodenet/standard#157]
Under headings for `what this does` and `what this doesn't do` we

Some go 
`Enable`
some
`Enables`
some
`Enabling`

-> something to fix? or fine?

**Comment by clausmullie** [comment]
See pull request #158 for example

**Comment by ElenaFdR** [comment]
Looking at the example, it seems like the problem we need to solve isn't just inconsistency in verb tenses - it's actually writing clearer sentences with more clear subjects and objects, no ambiguous pronouns, and potentially an active verb tense. I'd like to work through this with you (in person! side by side!) so we can define the rule/style (especially since it'll probably be relevant to other parts of the Standard). We can then also add it to the [style guide](https://github.com/publiccodenet/brand/issues/3).

**Comment by clausmullie** [comment]
Brilliant! Looking forward to it 🤠

**Comment by ericherman** [comment]
This work has been done.
