### ISSUE TITLE
Including examples in the standard

### ISSUE THREAD

**Issue by clausmullie** [publiccodenet/standard#162]
We have an example in Maintain Version Control -> Policy Makers

I quite like it. Should we aim to get examples everywhere? Or would that make it unwieldy? If the latter, should this one be removed?

**Comment by ElenaFdR** [comment]
Suggestions from Code for NL : 
- put small examples for how each role can meet the standard in their 'what you need to do' section (for example in Code in the open, give devs the example of using Git or Docker)
- add further reading links to case studies or more detailed examples of how a place/organization implemented this standard (so that the standard doesn't depend on the detailed/technical implementation info).

**Comment by Ainali** [comment]
This is the topic for the Community call for Thursday June 3, 13.00 UTC. See this link for how to join: https://hackmd.io/-OegeqvoThCbAsw3c3gIjw

**Comment by Ainali** [comment]
We also have more things that relates to the examples, like; templates, tools, processes, case studies, etc.

Right now, we find some of this in further reading. As we are imagining more learning resources and more resources for the stewards on how we work with the standard, some of these may fit better there than in the standard, but some should perhaps be duplicated as they might be good to have at hand in any particular entry point. Does any of these deserve their own heading, perhaps a combined new heading, or should we cram whatever we want to add in the body of the text or further reading?

**Comment by Ainali** [comment]
Since  we now have the [Community built implementation guide for the Standard for Public Code](https://github.com/publiccodenet/community-implementation-guide-standard) I will close this issue as examples (even in bulk) can go there.
