### ISSUE TITLE
role for residents

### ISSUE THREAD

**Issue by MirjamvT** [publiccodenet/standard#199]
Should we allow for/promote a role (to be defined) for residents (who are not also policy makers, management, developers or designers), in the standard?
And what should that role be?

**Comment by bvhme** [comment]
Hey @MirjamvT,

Thanks for the suggestion. In order to make it easier to write this document we chose to focus on a group of people who are 'in the loop' and are actually touching the technical aspects.

I feel directing content towards citizens as well will complicate the writing quite a lot and is better served in a different publication.

However, we can think about criteria that require the involved parties to think about their residents, although, that is always hard to not make political.

I'm closing this for now.
