### ISSUE TITLE
CLAs and holding copyrights

### ISSUE THREAD

**Issue by Beanow** [publiccodenet/standard#211]
In order to enforce (or change) a license, you need to have the copyrights for the code the claim is about. Especially when you decide a copyleft license like the GPL is in the spirit of the project goals, you will likely need to ask contributors to sign a [CLA](https://en.wikipedia.org/wiki/Contributor_License_Agreement), should you ever want to take legal action, for example against an entity that doesn't publish their changes.

Holding all the copyrights of a project is a powerful thing though. In Public Code's case you may want to require only a foundation is allowed to have this, and they should commit to using it for the benefit and sustainability of the community and be held accountable.

**Comment by bvhme** [comment]
@Beanow, I think you are very right about that, we haven't really written anything on this topic yet as we are still exploring whether the situation where no single actor can change the license might actually be more desirable for some cases and whether we perhaps don't have such a clear opinion on this. For codebases under our stewardship however we might need to think about this, and how to create the right amount of trust with this.

**Comment by ElenaFdR** [comment]
Suggestion from Code for NL meetup:
- add requirement to include a contributor licence agreement on a codebase (with links to arguments for different approaches)

**Comment by marctjones** [comment]
Just some general comments on how I have seen CLAs used.

**Comment by marctjones** [comment]
Just some general comments on how I have seen used CLAs. 

1) The Free Software Foundation no longer requires copyright assignment to contribute to projects. That was originally done in the 90s because at the time there was some concern it would not be possible to enforce the license on the project if one actor did not hold all of the copyrights. My understanding is that FSF still does require copyright assignments on some of its GNU projects but very few and for a combination of reasons including historical practice. At least in the United States you will not find many nonprofit projects collecting copyright assignments because they believe they need it to enforce the license.

2) The most common CLA seems to be Apache ICA and CCA and does not assign copyright ownership. It just offers a pretty broad grant. It is pretty well tolerated in the US if it is used by charitable nonprofits since the license granted is limited to the charitable mission of the nonprofit. It is more often criticized when adopted by companies such as Google since the charitable limit on the license is no longer present and essentially it coverts it to a unlimited rights license. The main reason for adopting the Apache style CLA is not for license enforcement but rather for relicensing. So for instance when the Apache foundation released version 2 of the Apache License it made it easier to upgrade all of the Apache Foundation's foundations projects from version 1 of the Apache license to version 2. Private companies also adopt it for that reason, since as we saw mostly recently with MongoDB it gives them the ability to relicense the project unilaterally. Private companies also like it because it allows them to maintain a proprietary version of the software side by side with the open source version individuals are contributing to. 

3) Github does have a CLA of sorts baked into the Users T&Cs (keep in mind this might not be a sufficient replacement for a corporate contributor agreement). If I remember correctly it basically says when you contribute to a repo on GitHub you are agreeing to license it under the license of the project if it has adopted a license. See Section 6 of the [GitHub Terms of Service](https://help.github.com/en/articles/github-terms-of-service). So in that respect it is actually closer to what the advocates of the DCO want.  This is sometimes called license in and license out. I think it is pretty closely associated with the Software Freedom Conservancy and the Linux kernel project. 

4) In the US it seems very well accepted that the license in and license out model is sufficient rights for people to enforce the license. You do not need to get permission from each contributor to go enforce the license, Still some open questions but I don't think many lawyers in the US are worried about them in the generic case. 

5) Many projects like adopting the license in and license out model and leaving copyright ownership with contributors _because_ it makes it harder to change the license. The conventional wisdom is that people are more likely to contribute since they know what terms their contribution will be licensed under and it makes it harder for a bad actor to take control of the project and change the licensing terms out from underneath contributors. And yes that does happen or at least there have been disputes about that happening. Although doesn't really matter if it does or not since developers have the concern so it is something a lot of developers look out for.  

6) The Any later version clause that was made popular by GPL and now widely include in other popular copyleft licenses is probably the best accepted way for dealing with coordinating a community code bases license change. For example if you look at Drupal it is licensed under GPLv2 or any later version. So users have the option of forking and creating projects licenses GPLv2 only or GPLv3 only or GPLv3 or later, or even switching to AGPLv3. I think it is with the expectation that if the license was ever going to change it would change to something that did not exist at the time the project was originally licensed and that it would be some kind of upgrade along the same lines. 

7) Most community projects control the licensing and enforcement by  1) picking the license it is distributed under 2) being a major copyright holder which gives them the ability to enforce the license and 3) moral authority with the respect of the contributor community. 

For what it is worth outside of the US federal government that doesn't have a coherent policy on which license to us and the UK government a lot of governments are adopting copyleft. The EU Public License for example is a official EU license that is copyleft and is GPL compatible. The State of California requires that its code by copylefted.

**Comment by bvhme** [comment]
Thanks so much for your comments, we're trying to figure out how to involve our members in this discussion as well since it feels pretty crucial.

**Comment by ElenaFdR** [comment]
Our 30 August 2019 community call focused on [this issue](https://github.com/publiccodenet/standard/issues/211) and [this pull request](https://github.com/publiccodenet/standard/pull/255) on CLAs. We’re especially interested in others’ experiences of CLAs to help us decide how to include them in the Standard. This is the community call summary.

 The people on the call were:

* @Beanow from Sustainable Free and Open Source Communities (SFOSC)
* @petkivim from the Nordic Institute for Interoperability Solutions (NIIS)
* @ericherman, @bvhme and @elenafdr from the Foundation for Public Code

Petteri explained that X-Road and other NIIS projects require CLAs because they are key national infrastructure for NIIS members and partners. In addition, X-Road is used globally by over 10 other countries. NIIS is responsible for developing and distributing the software which is why they need to have sufficient legal rights in case any issues should arise. However, Petteri doesn’t use CLAs for his private projects to avoid administrative overhead and to keep contributing as easy as possible.

Robin explained that SFOSC in principle prioritises based on John Rawls’ ‘Justice as Fairness’, taking a moral approach to decisionmaking (especially in relationships of unequal power). Though SFOSC hasn't formally considered CLAs, Robin advises taking the course of action most advantageous to the weakest party - in this case, individual contributors are usually less powerful than public organizations. Further discussion is needed to determine whether a specific CLA or no CLA is more advantageous to the weakest party.

The conversation veered to responsible disclosure policies. There’s a tension between encouraging responsible disclosure by having an explicit responsible disclsoure policy, and laws in some countries that require public organizations to criminally prosecute if someone publicly exposes a significant security flaw (even if they didn’t know the magnitude when they raised the issue) if there is a policy that states this. Public organizations often have to execute their policy regardless of the circumstances.

Eric wondered whether including a relicensing provision in the codebase license (like GPL 3 or EU public licence 1.2 or later) would be sufficient to avoid needing to have a CLA.

The group discussed whether the Foundation needed to have a single stance on CLAs for all codebases (whether there’d be a central authority with strong rights to safeguard fair and equal policies), or whether codebase governance will be pragmatic and allow codebase-specific approaches (our current view). The involvement of public organizations changes this compared to more usual open source projects.

Robin asked whether having a public organizations involved in a project reduces the bus factor. Boris explained that public organizations can have very different approaches to their software, and that not all software is of the same size and importance. Working to the Standard for Public Code should mitigate the bus factor; this is one of the selling points of Foundation membership.

Petteri raised the question of which country’s laws cover a CLA. NIIS is registered in Estonia, so while its CLAs can be signed digitally from within Estonia, most international contributors need to post a signed paper CLA. This creates additional administrative complexity: both to manage the paper, and to manage only merging pull requests from people whose CLAs have been received. Eric mentioned a recent example where a big open source project discussed abandoning having a CLA on a small component as the postal barrier was too high.

Based on the discussion, we expect our approach will be strongly influenced by the legal requirements of the current owners of the first codebase under stewardship. We’ll continue to explore this as part of our codebase assessment and incubation process.

**Comment by ericherman** [comment]
CLAs may intersect poorly with contributions from US federal employees, or employees of the British government.

https://www.law.cornell.edu/uscode/text/17/105
https://en.wikipedia.org/wiki/Crown_copyright#United_Kingdom

**Comment by ericherman** [comment]
This issue should have been closed with PR #313 which provided the text:

`* Contributors MUST NOT be required to transfer copyright of their contributions to the codebase.`
