### ISSUE TITLE
List of standards requirements in open-standards.md

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/standard#238]
It's significantly easier to test for this criterion if there's a list in the documentation. Is there any reason not to make this MUST?

> * The codebase SHOULD contain a list of all the standards used with links to where they are available

_Originally posted by @ElenaFdR in https://github.com/publiccodenet/standard/pull/227/files_

**Comment by ericherman** [comment]
Before making this a MUST, I believe we need to add nuance to the wording.

Having the list is certainly better, but what should that list contain?
How complete do we expect it to be?

If one were to make a truly complete list of standards employed by a codebase, it would add more "noise" than value because some standards, for instance TCP/IP, are so universal in most contexts that listing them is not going to help contributors.

We want a list of *meaningful* standards, those that a new contributor to a codebase would need to know about in order to make contributions which will not be rejected.

Perhaps it is most important to enumerate standards where there are competing options, or it is common to not adhere to one.
