### ISSUE TITLE
Consider rewording license choice for documentation

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/standard#269]
The requirement in [Publish with an open license](https://standard.publiccode.net/criteria/open-licenses.html): "Documentation MAY be published under Creative Commons licenses that are NOT ‘no derivatives’ or ‘non-commercial" has a tricky wording and also puts the bullet point far away from the super bullet point that applies to both code and documentation. Something in the line with "Documentation MUST NOT be published under Creative Commons licenses with the permissions ‘no derivatives’ or ‘non-commercial" might be better.

**Comment by bvhme** [comment]
I think that makes sense. In the end the goal of this is to prevent people choosing licences such as 'cc-by' or 'cc-nc' that restrict forking and continuous development of the codebase.

**Comment by Ainali** [comment]
Just to clarify, you meant 'cc-nd' and 'cc-nc', right?

**Comment by bvhme** [comment]
Definetely 'cc-nd' :)

And I'm wondering, wouldn't CC-BY also break forks, I thought it was incompatible with Open Source licenses, partly due to the requirement to indicate what you've changed. Although that seems pretty much inline with the version control requirement.

Also what about the alledged GPL incompatibility of CC-BY-SA? I don't seem to be able to wrap my head around this.

**Comment by bvhme** [comment]
But that is not this core issue.

**Comment by Ainali** [comment]
As far as I have understood it, the reason that CC BY and CC BY-SA is not used for software is that those were not designed for code (i.e. have nothing about patents etc.). They do qualify for the [open definition](https://opendefinition.org/licenses/). Note that OSI's site is under CC BY :) . 

CC BY-SA is compatible (in one direction) with GPL ([source](https://creativecommons.org/2015/10/08/cc-by-sa-4-0-now-one-way-compatible-with-gplv3/)).

**Comment by Ainali** [comment]
When thinking of it more, I believe this is redundant with:

> All code and documentation MUST be published under a license that allows it to be freely reusable, changeable and redistributable

**Comment by bvhme** [comment]
Enough so we can close this issue?

**Comment by Ainali** [comment]
If you prefer me creating a new issue for the redundancy, then sure.

**Comment by bvhme** [comment]
Sorry, I thought you thought the issue was redundant. And yes, I think the redundancy is true, this can be removed, however, I feel that this is still valuable guidance, so is there another place we could stash this?

On the original wording: I think it is important that we make clear we do think that creative commons licences are good, however, some licenses are not ok.

And yes, I meant :no_entry_sign: no derivatives and :no_entry_sign: non commercial :)

**Comment by Ainali** [comment]
Perhaps we can instead move to the section "Management: what you need to do?" Something like this?

Beware that even though Creative Commons licenses are great choice for documentation, not all variants for them are OSI-approved.

**Comment by bvhme** [comment]
Yeah, if only it was just management which did those things :p

I don't necessarily think the OSI approval is the most important part here, it is the indiscriminant reusability and changability. So I think we do need to name the licenses that are incompatible.

The first requirement for this criterion reads:

> All code and documentation MUST be licensed such that it may be freely reusable, changeable and redistributable.

Building off your sentence maybe something along the lines of:

* Beware that even though Creative Commons licenses are great for documentation licenses that stipulate Non-Commercial or No Derivatives are NOT freely reusable, changable and redistributable and don't fulfill these requirements.

**Comment by Ainali** [comment]
Yes, I like it. I just added one extra comma after documentation.

**Comment by bvhme** [comment]
I think it can be a period even :)

**Comment by bvhme** [comment]
Fixed in #334
