### ISSUE TITLE
Make the "Code in the open" MUST (unless used) more general applicable

### ISSUE THREAD

**Issue by felixfaassen** [publiccodenet/standard#324]
I'd like to report an issue in `criteria/code-in-the-open.md`

In the criteria is mentioned "All source code for any policy and software in use (unless used for fraud detection) MUST be published and publicly accessible."

May be we could rewrite this more broadly. There might be policy or software which cannot be open due to laws prohibiting that which go beyond fraud detection (think of national security and law enforcement in general)  

Proposed change:

All source code for any policy and software in use MUST be published and publicly accessible unless used for national security and or law enforcement purposes which require secrecy in order to function as mandated by the constitution and laws within the applicable jurisdiction.
 
If we can think of a plain English version of the above that would be great ;-)

**Comment by Ainali** [comment]
Hmm, could a codebase, which in its entirety was used for national security and therefore not being published at all, then pass the criteria and be considered compliant with the Standard for Public Code?

**Comment by felixfaassen** [comment]
Good point, I clearly yet do not understand this criteria ;-)  To answer your question:  I think policy or code which is not open (or cannot be open because of law and regulations) cannot be compliant with the Standard for Public code. But I can understand this needs more discussion

I get confused here because fraud detection is explicitly mentioned and excluded. To borrow your excellent question: Could a codebase, which in its entirety was used for fraud detection and therefore not being published at all, then pass the criteria and be considered compliant with the Standard for Public Code?

I think the same answer applies to that question. So maybe we should remove the unless clause and add a criteria which explicitly mentiones that source code which cannot made open mandated by law and regulation cannot pass this criteria if we all agree that this should be the case

**Comment by bvhme** [comment]
This is an interesting question.

The goal here was perhaps to give guidance as part of the requirement because the guidance is so crucial to making the point. That was probably a bad idea and this should be split up.

I think moving beyond 'fraud detection' might be a good idea since it is a very UK-centric thing. However, I think we could add a clause about 'as permitted by the law' which would then indeed add most of the national security things in there.

As for whether the code that fails this check can be standard compliant, probably not. However, something could be said for opening up secret codebases as much as possible without endangering national security by publishing components, like GCHQ and the NSA famously do.

**Comment by felixfaassen** [comment]
@bvhme and @Ainali what do you think of stating it like this:

All source code for any policy and software in use MUST be published and publicly accessible. 
Source code for software in use for national security and or law enforcement purposes which require secrecy in order to function as mandated by law SHOULD be published and publicly accessible. 

I'm still struggling how to write this down without making a  political statement and instead have a neutral description which tries to capture what Boris mentioned about secret codebases.

**Comment by bvhme** [comment]
I think framing it as 'within the fullest extend of the law the law' and exempting 'fraud detection' should cover this.

I think 'law enforcement' and 'national security' make it political since the definitions of those are very vague and are determined per country in laws if necessary. For fraud detection there is a clear causal link between it being open and being problematic. 

A lot of national security sensitive code can even benefit from being open, see GCHQ and NSA's open source efforts. Laws usually regulate what needs to be closed in these cases, through mechanisms as 'state secrets'.

**Comment by bvhme** [comment]
Perhaps something like:

> All source code [...], wherever permitted by the law, MUST be published and publicly accessible with the exception of source code used for fraud detection.

**Comment by felixfaassen** [comment]
@bvhme I really like your proposal. Less words, easy to understand and political neutral. I still do not understand why fraud detection exception should be mentioned as an unless clause.  I think by removing the "unless" clause you also cover the scenario of those kind of systems right?

So could this suffice:
All source code [...], wherever permitted by the law, MUST be published and publicly accessible.

**Comment by bvhme** [comment]
Fraud detection code and algorithms are a case where knowing the algorithm can defeat it's purpose, so it is generally exempt from these kinds of rules without a legislative foundation.

I've taken this largely from the [UK Government Digital Service's guidance on what should be secret](https://www.gov.uk/government/publications/open-source-guidance/when-code-should-be-open-or-closed).

**Comment by felixfaassen** [comment]
So when we refer here to "fraud detection" we are not referring to an entire code base but just the pieces of code and algorithms which reveal it's function and purpose. That to me was unclear from the start ;-) If that is the case I think we should state explicitly  what about:

All source code [...], wherever permitted by the law, MUST be published and publicly accessible with the exception source code implementing fraud detection functions and/or algorithms.

I'm looking for a sentence to specifically mention only the parts of the source code implementing fraud detection. So it is clear a codebase excluding the code and algorithms implementing fraud detection can still pass this criteria

**Comment by ElenaFdR** [comment]
I have a concern that adding language about the law introduces more complexity than clarity. 

This is because:
- nobody who's interacted with us so far has raised a concern about security and law enforcement public code (so no user need so far)
- generally civil servants are inclined be more conservative with data and more secretive about their work than what is permitted by law, rather than too permissive

Does adding 'wherever permitted by the law' make it easier to use our Standard, for us or anyone else? For example, does this give an out to a codebase to never work towards cleaning up any parts of the codebase that may include non-GDPR compliant information - because it's ok to not publish it? Would we feel comfortable stewarding a mature codebase with large portions of the code missing?

**Comment by Ainali** [comment]
> For example, does this give an out to a codebase to never work towards cleaning up any parts of the codebase that may include non-GDPR compliant information - because it's ok to not publish it?

Related to this, but also independent of this issue, when assessing a codebase, would we take a community's word for that portions of code are kept secret for reasons like this or would we want to verify that it is not some other code (that could be published) in those parts? Ie. would we as stewards like to have access to the entire codebase, even if not all of it can be published?

**Comment by ericherman** [comment]
So far we have not received any feedback from a public organization that the clause is too broad and would be improved by a "where permitted by law" or similar addition.

Also, so far we have not seen any codebase communities taking an overly broad interpretation of "unless used for fraud detection".

As the suggestions so far have not been an obvious win, @Ainali  and @ericherman  suggest closing this issue and re-opening when we have some concrete examples.
