### ISSUE TITLE
Possible redundancy and/or conflating requirements

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/standard#332]
We have two requirements that are very similar, to the point that it might make sense in either clarifying them to make them easier to distinguish from each other or possibly even merge if they are not meant to be different. It is:

1. [Code in the open](https://standard.publiccode.net/criteria/code-in-the-open.html)
>All source code for any policy and software in use (unless used for fraud detection) MUST be published and publicly accessible.

2. [Bundle policy and source code](https://standard.publiccode.net/criteria/bundle-policy-and-code.html)
>A codebase MUST include all source code that the policy is based on.

As I read it, I cannot see what 2. adds beyond 1.
If 1. is passed, 2. is passed and if 1. is failed, 2. is failed.

Unless, of course, 1. is failed because source code for software is not being published, which suggests that 1. should actually be two separate requirements. 

My question is: should we split 1. into two requirements (one for policy and one for software) and remove 2.? Or have I misunderstood something?

**Comment by bvhme** [comment]
First of all the Standard to be based on the criteria rather than the requirements. Every criterion is a need to be filled that comes with requirements to make sure it is. This means that redundancy between criteria can occur since similar things might be necessary to fulfill those needs. I fear that breaking this down would, although making it easier to use for hardened power users, would make it almost inaccesible for newcomers since our thinking behind the requirements would be disconnected.

For this one however, I think that although they are aligned with the topic of transparency they try to require a similar thing with a very different goal:

## 1. Code must be open when in use
This is meant to make sure the codebase is published, along with everything in it whenever it is used. E.g. running code should always be a public version, not your secret hacked fork.

## 2. Code must include policy it is based on and vice versa
This is meant to make sure that the reasoning for the development of the code and policy in this way is not removed as it is often necessary to judge replicability for re-users as well as to judge the quality of the implementation for those scrutinizing the code.

Specifically, the first two requirements in [Bundle policy and source code](https://standard.publiccode.net/criteria/bundle-policy-and-code.html) mean to accentuate:

* If you are basing the code on policy, the policy is part of the codebase; and
* If you are basing part of the policy on the code, that code is part of the codebase

Does that make it clearer @Ainali? Perhaps we could reword these entries to make this clearer. I know that _Bundle policy and source code_ is quite the difficult criterion.

**Comment by Ainali** [comment]
Isn't the second bullet point redundant in itself? If I write a bit longer:

If you are basing part of the policy on some code in your codebase, that code in your codebase is part of the codebase.

If not, it feels like I, and the Standard, are missing some other context.

**Comment by bvhme** [comment]
They can both be true or not individually from each other, and probably are most often.

So two examples:

* A computer programme that executes parking policy by sending people fines if they drive to fast (software implementing policy)
* A law that is based on a software model (policy implementing software)

So one is your statement up there and the other the reverse. 

My intention here was to prevent the following two cases:

> This codebase only needs to contain the policy, not the source code we've based that on

or

> This codebase only needs to have the source code, not the policy we've based that on

**Comment by Ainali** [comment]
> They can both be..

I am not sure what the "they" is referring to anymore. Something in my last comment?

**Comment by bvhme** [comment]
Both requirements

**Comment by ericherman** [comment]
By having the exception for fraud detection in "Code in the open" but not in "Bundle policy and code", there is a lack of clarity in the situation where there is software based on policy that includes fraud detection.

We have a work session scheduled on 26 July, react with a :rocket: if you wish an invite.

**Comment by ericherman** [comment]
After more discussion, @Ainali and @ericherman concluded that the redundancy may help with clarity, and thus we should close this issue for now, and open a more targeted issue for adding the fraud detection exemption to Bundle policy and code.

See https://github.com/publiccodenet/standard/issues/676
