### ISSUE TITLE
URL `bpmnquickguide.com` not reachable from Travis

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/standard#338]
Travis seems to be blocked from `bpmnquickguide.com` leading to the tests failing. The tests pass on my machine.

Error code 0 might mean something is wrong on the configuration of the Travis though, because it might indicate that an outside server is never reached and thus there is no HTTP error code. Alternatively they could not be returning one like LinkedIn does.

Log from [Travis build 885](https://travis-ci.com/github/publiccodenet/standard/builds/169770532):

```
- ./_site/criteria/bundle-policy-and-code.html

  *  External link https://www.bpmnquickguide.com/view-bpmn-quick-guide/ failed: response code 0 means something's wrong.

             It's possible libcurl couldn't connect to the server or perhaps the request timed out.

             Sometimes, making too many requests at once also breaks things.

             Either way, the return message (if any) from the server is: Peer certificate cannot be authenticated with given CA certificates

htmlproofer 3.15.3 | Error:  HTML-Proofer found 1 failure!

The command "./script/cibuild.sh" exited with 1.
```

**Comment by bvhme** [comment]
As this looks like an SSH error, there might also be something wrong with that.

**Comment by felixfaassen** [comment]
Hi @bvhme I've fixed this issue when trying to merge #325. 

Please see solution and fix here:
https://github.com/publiccodenet/standard/pull/329#issuecomment-639370549

short gist: instructed htmlproofer to not fail on external SSL cert host checking. If you still want to have builds break on checking external SSL certs I also have a solution for that let me know

**Comment by felixfaassen** [comment]
for clarity here a copy paste of the fix

Build broke on:

> ./_site/criteria/bundle-policy-and-code.html
> 
> External link https://www.bpmnquickguide.com/view-bpmn-quick-guide/ failed: response code 0 means something's wrong.
> It's possible libcurl couldn't connect to the server or perhaps the request timed out.
> Sometimes, making too many requests at once also breaks things.
> Either way, the return message (if any) from the server is: Peer certificate cannot be authenticated with given CA certificates
> htmlproofer 3.15.3 | Error: HTML-Proofer found 1 failure!
> The command "./script/cibuild.sh" exited with 1.

I added a config line to HTML proofer to disable external SSL host/cert checking which can break builds when either the external host uses outdated SSL certs OR external hosts use SSL certs our travis container cannot verify as it might be missing the latest CA certs. In this case the cert is valid and the problem lies in the instance at travis not having the latest root ca certificates available.

See test.sh for changes (and commit log). Additional solution could be to add an extra command to the .travis_yml by having the certs updated each time travis spins up a container but this requires root priveles meaning builds will go much slower.

this is the new line:
bundle exec htmlproofer --url-ignore "/github.com/(.*)/edit/" ./_site --typhoeus-config '{"ssl_verifypeer": false, "ssl_verifyhost":0}'

@bvhme if you agree on this solution you can close.

**Comment by felixfaassen** [comment]
closed. In future build fixes should be in seperate issues not mixed with pull requests or other issues
