### ISSUE TITLE
Add UK Open Standards Principles to Further Reading on Use Open Standards

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/standard#464]
https://www.gov.uk/government/publications/open-standards-principles/open-standards-principles

Or the equivalent from other countries!

I expect that showing positive encouragement from other countries will be helpful to policy and management.

**Comment by Ainali** [comment]
I like this. It might also be informative for some readers of the Standard what policies are in place in your own country. I guess we can start by listing them in the standard, and if it later turns out that it becomes unwieldy because too many countries have policies like this in place, we can make a list somewhere and just point to that list from the Standard.

**Comment by ericherman** [comment]
d356ab641ff77d02948a719fdffdbb986d65aa3f
