### ISSUE TITLE
Style: standardise on `.` at the end of a list-rule or not.

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/standard#48]

**Comment by ElenaFdR** [comment]
I suggest adding a period so that we have the option of adding a second sentence if we need to without introducing grammatical inconsistency. This may also be easier for contributors to get right the first time, as it's closer to how people are taught to write.

**Comment by bvhme** [comment]
Sure, as long as we are consistent

(I do find having the option to add a second sentence allows you to be less
consise though)

**Comment by ElenaFdR** [comment]
'Reusable and portable code' has a second sentence for an example, which works quite well. We can strongly discourage second sentences for any other purposes.

**Comment by Ainali** [comment]
I don't have any strong opinion on whether or not to always end with "." but I do have a strong opinion that we should be consistent within the same document. So a temporary solution for the next release on either removing them all or adding on all would make sense to me, even if later decide to change it back. As of now, since there are inconsistencies over chapters and headings alike, it just looks like we have missed to take this under consideration.

**Comment by bvhme** [comment]
I agree, my choice would be, as Elena suggested, to put periods after everything.
