### ISSUE TITLE
Review the use of 'reuse'

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/standard#543]
The overall purpose of the standard is to enable collaboration between public organizations. However, we seem to often (but not everywhere) use the word 'reuse' in many cases where it really should say 'collaboration'.

We should review the entire standard to make sure that we are using the right word in each of these places.

(@ericherman and I discovered this when working on the explanation of why international ambitions are important)

**Comment by bvhme** [comment]
To nuance this, I think the Standard needs to align with the goal of our organization, as I think it's not only Collaboration that it tries to enable. The goal of the Standard should be ['to support collective development and maintenance of public code in order to reduce risk, increase quality, reduce cost and increase sustainability'](https://about.publiccode.net/organization/articles-of-association.html#article-3-purpose-and-methodology). Pure collaboration is an important aspect of collective development and maintenance but not everything.

I think this is very indispensable, as I think an significant path to collaboration can be through aligning with the Standard first and then being open to collaboration, instead of requiring it to be the other way around.

**Comment by Ainali** [comment]
Yes! And even with that thought in our head, I think there are still some places where we wrote reuse when we actually meant collaboration.

**Comment by Ainali** [comment]
We also touched upon this in the last communit call: https://blog.publiccode.net/community%20call/2021/12/13/notes-from-community-call-2-december-2021.html
