### ISSUE TITLE
"machine-readable" or "machine readable"

### ISSUE THREAD

**Issue by ericherman** [publiccodenet/standard#588]
Today the standard includes "machine-readable" in some places and "machine readable" in others.

**Comment by Ainali** [comment]
Which version do we want? "machine readable" seems to [be the one most widely used](https://trends.google.com/trends/explore?q=machine-readable,%22machine%20readable%22).

**Comment by ericherman** [comment]
I'd like to stand on ground more firm that "everyone else is doing it". That said, there is no legal authority to govern the Amercan English language, thus that is not totally unreasonable.

https://www.merriam-webster.com/words-at-play/hyphen-rules-open-closed-compound-words cover the topic of popular drift:

> Historically, a lot of compounds follow the pattern of entering English as open compounds, then gradually take on hyphenation and eventually a closed form as they become more familiar. There was a time, after all, when baseball was spelled as base ball. As the sport took hold in the American consciousness, it gradually began to be spelled with a hyphen (base-ball), but now any form other than the solid compound baseball looks like an affectation.

**Comment by Ainali** [comment]
So, do we want to be progressive or conservative in our US English?

**Comment by ericherman** [comment]
If we can't find a better footing than the popular usage on the internet, then rather than "progressive or conservative" I would rather think in terms of what is most accessible for all readers, especially non-native readers. With that in mind, hyphenation would be more explicit.

**Comment by ElenaFdR** [comment]
I also vote for hyphenated for now, because the Standard often uses 'machine readable' in longer, more complicated sentences - either modifying 2 nouns, or in a string of adjectives.
Things I considered along the way:
- [Merriam Webster hyphenates machine-readable](https://www.merriam-webster.com/dictionary/machine-readable)
- 'Machinereadable' as 1 word hasn't arrived yet, according to [Google Trends](https://trends.google.com/trends/explore?q=machine-readable,%22machine%20readable%22,machinereadable)
- Both [the Guardian](https://www.theguardian.com/guardian-observer-style-guide-h#hyphens) and [GDS](https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style#hyphenation), which I rate highly for valuing clear writing, both recommend only using hyphens where there's the possibility for confusion, and so would advise us not to do it
