### ISSUE TITLE
Maintain version control: do we care which version control system they use?

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/standard#66]
Do we want to prescribe what the version control schema is?

GDS requires semantic versioning:
https://semver.org/

**Comment by bvhme** [comment]
I think semver is a good default, I love MINOR.MAJOR.PATCH. Starting at
version 0.1 for now.

Alternatively we might want to choose a version type that shows how we plan
to develop it. For example one major version per year labelled 2019.X.X or
something.

**Comment by bvhme** [comment]
O, I think I misunderstood the issue as being about the version of the _standard_ itself.

For what versioning system is used I would prefer semantic versioning, however there are valid reasons to use different versioning strategies. For me the advantage of using semantic versioning is mostly about standardisation and being understandable, which is why we could require it.

In the end I love semantic versioning if followed well, however it requires [some serious dedication](http://faq.sealedabstract.com/why_not_semver/).

**Comment by ElenaFdR** [comment]
I'm persuaded we don't need to tell people which versioning scheme to use - the 'further reading' links provide a comprehensive explanation of versioning. 'Why not semver' also makes good points.
