### ISSUE TITLE
Review 'further reading' for 'Create reusable and portable code'

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/standard#686]
Are all of these still relevant here, or would some of these fit better in the documentation criteria?

**Comment by Ainali** [comment]
Now I have looked at them again and I think that 

* [OpenAPI Specification](https://spec.openapis.org/oas/latest.html)
* [Internationalization techniques: Authoring HTML & CSS](https://www.w3.org/International/techniques/authoring-html)
* [GNU gettext](https://www.gnu.org/software/gettext/gettext.html)

can all move to the implementation guide as they are more details of how to implement something rather than general further reading.
